apiVersion: v1
kind: ConfigMap
metadata:
  name: naive-strategy
data:
  bootstrap_servers: "pkc-ep9mm.us-east-2.aws.confluent.cloud:9092"
  group_id: "naive-strategy"
  input_topic: "minute-aggregates"
  output_topic: "intended-trades"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: naive-strategy-deployment
spec:
  selector:
    matchLabels:
      app: naive-strategy
  replicas: 1
  template:
    metadata:
      labels:
        app: naive-strategy
    spec:
      containers:
      - name: naive-strategy
        image: 799439856592.dkr.ecr.us-east-1.amazonaws.com/naive-strategy:${IMAGE_TAG}
        env:
        - name: SASL_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka
              key: SASL_USERNAME
        - name: SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka
              key: SASL_PASSWORD
        - name: BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: naive-strategy
              key: bootstrap_servers
        - name: GROUP_ID
          valueFrom:
            configMapKeyRef:
              name: naive-strategy
              key: group_id
        - name: INPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: naive-strategy
              key: input_topic
        - name: OUTPUT_TOPIC
          valueFrom:
            configMapKeyRef:
              name: naive-strategy
              key: output_topic
        - name: SECURITY_PROTOCOL
          value: "SASL_SSL"
        - name: SASL_MECHANISMS
          value: "PLAIN"
        - name: RUST_LOG
          value: "debug"
        - name: ACCOUNT_UPDATES
          value: "true"
        - name: TRADE_UPDATES
          value: "true"
